### ISSUE TITLE
GenomicRanges=>SnaptronQueryBuilder support

### ISSUE THREAD

**Issue by ChristopherWilks** [langmead-lab/snapr#1]
It would be great if Snapcount could take a GenomicRanges object of one or more ranges and create a list of SnaptronQueryBuilder objects, one per input range.  As part of this, it would be good if the function to do this could support defining one set of filters (range & sample) and a coordinates modifier (e.g. exact) that would apply to the whole set of ranges.  That way, the user could submit a set of ranges that will all have the same filters and/or modifier applied when queried.

**Comment by ch4rr0** [comment]
This has already been implemented, albeit slightly different than described here. Snapcount can accept a GenomicRange object and will return a list of results to the user. The user can opt to merge the results into one table or SummarizedExperiment depending on their choice of output.
